"""empty message

Revision ID: 98d5f171b53a
Revises:
Create Date: 2019-11-21 06:56:32.497039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98d5f171b53a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
                    sa.Column(
                        'id',
                        sa.Integer(),
                        autoincrement=True,
                        nullable=False),
                    sa.Column('todo_content', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('todo_content')
                    )
    op.create_index(op.f('ix_todo_id'), 'todo', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_id'), table_name='todo')
    op.drop_table('todo')
    # ### end Alembic commands ###
